/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: efKYYURoqLp2Ndnjoji8Cj
// Component: S8Kkj3_4a1F3

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";
import * as plasmicAuth from "@plasmicapp/react-web/lib/auth";

import { usePlasmicDataSourceContext } from "@plasmicapp/data-sources-context";

import { Embed } from "@plasmicpkgs/plasmic-basic-components";
import { NavigationBar } from "@plasmicpkgs/plasmic-nav";
import Button from "../../Button"; // plasmic-import: 0xgMYo2lU1H9/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: efKYYURoqLp2Ndnjoji8Cj/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: efKYYURoqLp2Ndnjoji8Cj/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: efKYYURoqLp2Ndnjoji8Cj/projectcss
import sty from "./PlasmicProjects.module.css"; // plasmic-import: S8Kkj3_4a1F3/css

import Icon4Icon from "./icons/PlasmicIcon__Icon4"; // plasmic-import: Fzv2z5kRmYBK/icon
import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: s_87OGbueP2l/icon
import FacebookSvgrepoComSvgIcon from "./icons/PlasmicIcon__FacebookSvgrepoComSvg"; // plasmic-import: 7UuVZE22RoDF/icon
import Icon28Icon from "./icons/PlasmicIcon__Icon28"; // plasmic-import: 46OHjqaCc92u/icon

createPlasmicElementProxy;

export type PlasmicProjects__VariantMembers = {};
export type PlasmicProjects__VariantsArgs = {};
type VariantPropType = keyof PlasmicProjects__VariantsArgs;
export const PlasmicProjects__VariantProps = new Array<VariantPropType>();

export type PlasmicProjects__ArgsType = {};
type ArgPropType = keyof PlasmicProjects__ArgsType;
export const PlasmicProjects__ArgProps = new Array<ArgPropType>();

export type PlasmicProjects__OverridesType = {
  projects?: Flex__<"div">;
  navigationBar?: Flex__<typeof NavigationBar>;
  slateArro?: Flex__<typeof PlasmicImg__>;
  button?: Flex__<typeof Button>;
  ecosystemFooter2?: Flex__<"div">;
  columns?: Flex__<"div">;
};

export interface DefaultProjectsProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicProjects__RenderFunc(props: {
  variants: PlasmicProjects__VariantsArgs;
  args: PlasmicProjects__ArgsType;
  overrides: PlasmicProjects__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const currentUser = useCurrentUser?.() || {};

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary_large_image" />
        <title key="title">{PlasmicProjects.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicProjects.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicProjects.pageMetadata.title}
        />
        <meta
          key="description"
          name="description"
          content={PlasmicProjects.pageMetadata.description}
        />
        <meta
          key="og:description"
          property="og:description"
          content={PlasmicProjects.pageMetadata.description}
        />
        <meta
          key="twitter:description"
          name="twitter:description"
          content={PlasmicProjects.pageMetadata.description}
        />
        <meta
          key="og:image"
          property="og:image"
          content={PlasmicProjects.pageMetadata.ogImageSrc}
        />
        <meta
          key="twitter:image"
          name="twitter:image"
          content={PlasmicProjects.pageMetadata.ogImageSrc}
        />
        <link rel="canonical" href={PlasmicProjects.pageMetadata.canonical} />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"projects"}
          data-plasmic-override={overrides.projects}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.projects
          )}
        >
          <Embed
            className={classNames("__wab_instance", sty.embedHtml__egBnE)}
            code={
              '<script type="application/ld+json">\n{\n  "@context": "https://schema.org",\n  "@type": "CreativeWork",\n  "name": "Futuro Projects",\n  "url": "https://futuro.ngo/projects",\n  "description": "Social impact projects designed and incubated by young leaders, changemakers, and institutions across the Americas.",\n  "publisher": {\n    "@type": "Organization",\n    "name": "Futuro"\n  }\n}\n</script>'
            }
          />

          <NavigationBar
            data-plasmic-name={"navigationBar"}
            data-plasmic-override={overrides.navigationBar}
            brand={
              <PlasmicLink__
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.link__ypeh
                )}
                component={Link}
                href={"#"}
                platform={"nextjs"}
              >
                <PlasmicImg__
                  data-plasmic-name={"slateArro"}
                  data-plasmic-override={overrides.slateArro}
                  alt={""}
                  className={classNames(sty.slateArro)}
                  displayHeight={"40px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  onClick={async event => {
                    const $steps = {};

                    $steps["goToHomepage"] = true
                      ? (() => {
                          const actionArgs = { destination: `/` };
                          return (({ destination }) => {
                            if (
                              typeof destination === "string" &&
                              destination.startsWith("#")
                            ) {
                              document
                                .getElementById(destination.substr(1))
                                .scrollIntoView({ behavior: "smooth" });
                            } else {
                              __nextRouter?.push(destination);
                            }
                          })?.apply(null, [actionArgs]);
                        })()
                      : undefined;
                    if (
                      $steps["goToHomepage"] != null &&
                      typeof $steps["goToHomepage"] === "object" &&
                      typeof $steps["goToHomepage"].then === "function"
                    ) {
                      $steps["goToHomepage"] = await $steps["goToHomepage"];
                    }
                  }}
                  src={{
                    src: "/plasmic/futuro_ngo/images/slateD0ArroPng.png",
                    fullWidth: 750,
                    fullHeight: 750,
                    aspectRatio: undefined
                  }}
                />
              </PlasmicLink__>
            }
            className={classNames("__wab_instance", sty.navigationBar)}
            closeButton={
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img___2MDkI)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                src={"https://static1.plasmic.app/close.svg"}
              />
            }
            itemsGap={8}
            menuItems={
              <React.Fragment>
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link__aAfHe
                  )}
                  component={Link}
                  href={`/projects`}
                  platform={"nextjs"}
                >
                  {"Projects"}
                </PlasmicLink__>
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link__xrmxC
                  )}
                  component={Link}
                  href={`/partners`}
                  platform={"nextjs"}
                >
                  {"Partners"}
                </PlasmicLink__>
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link___20Nhd
                  )}
                  component={Link}
                  href={`/stories`}
                  platform={"nextjs"}
                >
                  {"Stories"}
                </PlasmicLink__>
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link__hv2Bc
                  )}
                  component={Link}
                  href={`/our-declaration`}
                  platform={"nextjs"}
                >
                  {"Our Declaration"}
                </PlasmicLink__>
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link___8RVa
                  )}
                  component={Link}
                  href={"https://www.benextglobal.com/FUTUROmmxxv"}
                  platform={"nextjs"}
                >
                  {"Log In"}
                </PlasmicLink__>
                <Button
                  data-plasmic-name={"button"}
                  data-plasmic-override={overrides.button}
                  className={classNames("__wab_instance", sty.button)}
                  color={"slateD0"}
                  end={
                    <Icon4Icon
                      className={classNames(projectcss.all, sty.svg__xEAl7)}
                      role={"img"}
                    />
                  }
                  iconEnd={true}
                  label={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___6Ioar
                      )}
                    >
                      {"Become a Partner"}
                    </div>
                  }
                  linkTo={`/partners`}
                  size={"large"}
                  start={null}
                />
              </React.Fragment>
            }
            openButton={
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__ckvO0)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "1px"
                    : "auto"
                }
                src={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? {
                        src: "/plasmic/futuro_ngo/images/slateD0MenuSvg.svg",
                        fullWidth: 12,
                        fullHeight: 12,
                        aspectRatio: 1
                      }
                    : "https://static1.plasmic.app/menu.svg"
                }
              />
            }
            responsiveBreakpoint={768}
          />

          <Embed
            className={classNames("__wab_instance", sty.embedHtml__aagkS)}
            code={
              '<section style="position: relative; width: 100%; margin: 0 auto; overflow: hidden;">\n    <!-- Wistia Background Embed -->\n  <div class="wistia_responsive_padding" style="padding:56.25% 0 0 0; position:relative;">\n    <div class="wistia_responsive_wrapper" style="height:100%; left:0; position:absolute; top:0; width:100%;">\n      <div class="wistia_embed wistia_async_twzdslp5dq videoFoam=true autoPlay=true muted=true loop=true playbar=false fullscreenButton=false controlsVisibleOnLoad=false" style="height:100%; width:100%">&nbsp;</div>\n    </div>\n  </div>\n  <script src="https://fast.wistia.net/assets/external/E-v1.js" async></script>\n\n  <!-- Hoya Blue Overlay -->\n  <div style="\n    background-color: rgba(1, 30, 65, 0.55);\n    position: absolute;\n    top: 0;\n    left: 0;\n    width: 100%;\n    height: 100%;\n    z-index: 2;">\n  </div>\n\n  <!-- Text Overlay -->\n  <div style="\n    position: absolute;\n    bottom: 2rem;\n    right: 2rem;\n    width: auto;\n    max-width: 90%;\n    text-align: right;\n    z-index: 3;">\n    <h1 style="\n      font-family: \'Oswald\', sans-serif;\n      font-weight: 700;\n      text-transform: uppercase;\n      color: #D0D0D0;\n      font-size: clamp(2.25rem, 7.5vw, 6rem);\n      line-height: 1.05;\n      margin: 0;">\n      Social<br>Impact<br>In Motion.\n    </h1>\n  </div>\n</section>\n\n<!-- Google Font Import -->\n<link href="https://fonts.googleapis.com/css2?family=Oswald:wght@700&display=swap" rel="stylesheet">'
            }
          />

          <div className={classNames(projectcss.all, sty.freeBox__s66Df)}>
            <div className={classNames(projectcss.all, sty.freeBox__fjYmT)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__qQrVz
                )}
              >
                {
                  "EVERY PROJECT YOU SEE HERE STARTED WITH A SINGLE VISION\u2013NOW IT SHAPES COMMUNITIES, NARRATIVES, AND POLICY."
                }
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__qv8EK
                )}
              >
                {
                  "Futuro serves as the global portfolio for projects born from the BeNeXT Global ecosystem. From climate resilience in Colombia to education reform in Kenya, each initiative is a living case study in transnational collaboration, narrative sovereignty, and social innovation.\n\nExplore:\n\t\u2022\tYouth-led Initiatives\n\t\u2022\tTech for Social Good\n\t\u2022\tHealth Equity & Access\n\t\u2022\tLegacy Projects by Seasoned Leaders\n\t\u2022\tCross-Institutional Collaborations\n\nEach project includes:\n\t\u2022\tOrigin story\n\t\u2022\tImpact milestones\n\t\u2022\tCurrent needs\n\t\u2022\tWays to get involved"
                }
              </div>
            </div>
          </div>
          <div
            data-plasmic-name={"ecosystemFooter2"}
            data-plasmic-override={overrides.ecosystemFooter2}
            className={classNames(projectcss.all, sty.ecosystemFooter2)}
          >
            <div
              data-plasmic-name={"columns"}
              data-plasmic-override={overrides.columns}
              className={classNames(projectcss.all, sty.columns)}
            >
              <div className={classNames(projectcss.all, sty.column___8IHlh)}>
                <div className={classNames(projectcss.all, sty.freeBox__qA88P)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img___9YjMa)}
                    displayHeight={"90px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"90px"}
                    src={{
                      src: "/plasmic/futuro_ngo/images/slateprofileArro2Png.png",
                      fullWidth: 750,
                      fullHeight: 750,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(projectcss.all, sty.freeBox__uvJt8)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__nLaaw
                      )}
                    >
                      {"Connect with us"}
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__a06Tc)}
                    >
                      <Icon3Icon
                        className={classNames(projectcss.all, sty.svg__bIizM)}
                        role={"img"}
                      />

                      <FacebookSvgrepoComSvgIcon
                        className={classNames(projectcss.all, sty.svg__gUWjL)}
                        role={"img"}
                      />

                      <Icon28Icon
                        className={classNames(projectcss.all, sty.svg__q7T67)}
                        role={"img"}
                      />
                    </div>
                  </div>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column___5MlD6)}>
                <div className={classNames(projectcss.all, sty.freeBox__grIcf)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__eo43C
                    )}
                  >
                    {"PROJECTS & IMPACT"}
                  </div>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__ypoPb
                    )}
                    component={Link}
                    href={`/projects`}
                    platform={"nextjs"}
                  >
                    {"Submit Your Project"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__v0R9P
                    )}
                    component={Link}
                    href={"https://www.plasmic.app/"}
                    platform={"nextjs"}
                  >
                    {"Changemaker Stories"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__dnPQ
                    )}
                    component={Link}
                    href={`/partners`}
                    platform={"nextjs"}
                  >
                    {"Global Collaborations"}
                  </PlasmicLink__>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__jM1F1)}>
                <div className={classNames(projectcss.all, sty.freeBox__oVe0Z)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___3IakI
                    )}
                  >
                    {"LEARN & ENGAGE"}
                  </div>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__bidX2
                    )}
                    component={Link}
                    href={`/our-declaration`}
                    platform={"nextjs"}
                  >
                    {"About"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link___37M3W
                    )}
                    component={Link}
                    href={`/partners`}
                    platform={"nextjs"}
                  >
                    {"Join the Movement"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__trm5P
                    )}
                    component={Link}
                    href={""}
                    platform={"nextjs"}
                  >
                    {"Become a Partner"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__jdrgs
                    )}
                    component={Link}
                    href={`/our-declaration`}
                    platform={"nextjs"}
                  >
                    {"Careers"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__ome7K
                    )}
                    component={Link}
                    href={`/projects`}
                    platform={"nextjs"}
                  >
                    {"Contact Us"}
                  </PlasmicLink__>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__vo6Ok)}>
                <div className={classNames(projectcss.all, sty.freeBox__ozinc)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__vzOrU
                    )}
                  >
                    {"THE ECOSYSTEM"}
                  </div>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__zUxUh
                    )}
                    component={Link}
                    href={`/`}
                    platform={"nextjs"}
                  >
                    <React.Fragment>
                      <React.Fragment>{"Futuro\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontStyle: "italic" }}
                      >
                        {"    Global Impact HQ"}
                      </span>
                    </React.Fragment>
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__kr4Di
                    )}
                    component={Link}
                    href={"https://www.benextglobal.com"}
                    platform={"nextjs"}
                    target={"_blank"}
                  >
                    <React.Fragment>
                      <React.Fragment>{"BeNeXT\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontStyle: "italic" }}
                      >
                        {"    The Model Rewritting Education"}
                      </span>
                    </React.Fragment>
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__rjU0
                    )}
                    component={Link}
                    href={"https://www.next.ngo"}
                    platform={"nextjs"}
                    target={"_blank"}
                  >
                    <React.Fragment>
                      <React.Fragment>{"NeXT\n"}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontStyle: "italic" }}
                      >
                        {"    The New Standard of Credentialing"}
                      </span>
                    </React.Fragment>
                  </PlasmicLink__>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__zhSY)}>
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link__ajww1
                  )}
                  component={Link}
                  href={"https://www.mitikah.co"}
                  platform={"nextjs"}
                  target={"_blank"}
                >
                  <React.Fragment>
                    <React.Fragment>{"M\u00edtikah\n"}</React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontStyle: "italic" }}
                    >
                      {"    Where Story Drives Strategy"}
                    </span>
                  </React.Fragment>
                </PlasmicLink__>
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link___5V2Dw
                  )}
                  component={Link}
                  href={"https://www.medikah.co"}
                  platform={"nextjs"}
                  target={"_blank"}
                >
                  <React.Fragment>
                    <React.Fragment>{"Medikah\n"}</React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontStyle: "italic" }}
                    >
                      {"    Our definitive Project in Human Wellbeing"}
                    </span>
                  </React.Fragment>
                </PlasmicLink__>
                <PlasmicLink__
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    sty.link__zaxOq
                  )}
                  component={Link}
                  href={"https://www.benextglobal.com/blog"}
                  platform={"nextjs"}
                  target={"_blank"}
                >
                  <React.Fragment>
                    <React.Fragment>{"Futuro Signal\n"}</React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontStyle: "italic" }}
                    >
                      {"    The Pulse of Global Change\u2013Decoded"}
                    </span>
                  </React.Fragment>
                </PlasmicLink__>
              </div>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  projects: [
    "projects",
    "navigationBar",
    "slateArro",
    "button",
    "ecosystemFooter2",
    "columns"
  ],
  navigationBar: ["navigationBar", "slateArro", "button"],
  slateArro: ["slateArro"],
  button: ["button"],
  ecosystemFooter2: ["ecosystemFooter2", "columns"],
  columns: ["columns"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  projects: "div";
  navigationBar: typeof NavigationBar;
  slateArro: typeof PlasmicImg__;
  button: typeof Button;
  ecosystemFooter2: "div";
  columns: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicProjects__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicProjects__VariantsArgs;
    args?: PlasmicProjects__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicProjects__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicProjects__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicProjects__ArgProps,
          internalVariantPropNames: PlasmicProjects__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicProjects__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "projects") {
    func.displayName = "PlasmicProjects";
  } else {
    func.displayName = `PlasmicProjects.${nodeName}`;
  }
  return func;
}

function withUsePlasmicAuth<P extends object>(
  WrappedComponent: React.ComponentType<P>
) {
  const WithUsePlasmicAuthComponent: React.FC<P> = props => {
    const dataSourceCtx = usePlasmicDataSourceContext() ?? {};
    const { isUserLoading, user, token } = plasmicAuth.usePlasmicAuth({
      appId: "efKYYURoqLp2Ndnjoji8Cj"
    });

    return (
      <PlasmicDataSourceContextProvider__
        value={{
          ...dataSourceCtx,
          isUserLoading,
          userAuthToken: token,
          user
        }}
      >
        <WrappedComponent {...props} />
      </PlasmicDataSourceContextProvider__>
    );
  };
  return WithUsePlasmicAuthComponent;
}

export const PlasmicProjects = Object.assign(
  // Top-level PlasmicProjects renders the root element
  withUsePlasmicAuth(makeNodeComponent("projects")),
  {
    // Helper components rendering sub-elements
    navigationBar: makeNodeComponent("navigationBar"),
    slateArro: makeNodeComponent("slateArro"),
    button: makeNodeComponent("button"),
    ecosystemFooter2: makeNodeComponent("ecosystemFooter2"),
    columns: makeNodeComponent("columns"),

    // Metadata about props expected for PlasmicProjects
    internalVariantProps: PlasmicProjects__VariantProps,
    internalArgProps: PlasmicProjects__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "Futuro Projects | Social Impact Built and Scaled",
      description:
        "Curated, measurable initiatives across the Americas—incubated with institutions that invest in change.",
      ogImageSrc:
        "https://site-assets.plasmic.app/050c9095a9c42e8f9e09bf51b54aae39.png",
      canonical: "https://futuro.ngo/projects"
    }
  }
);

export default PlasmicProjects;
/* prettier-ignore-end */
