/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: efKYYURoqLp2Ndnjoji8Cj

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantshHpOgzCwvkyU } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: HHpOGZCwvkyU/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantshHpOgzCwvkyU
});
