// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicButton,
  DefaultButtonProps
} from "./plasmic/futuro_ngo/PlasmicButton";

export type ButtonProps = DefaultButtonProps;

function Button(props: ButtonProps) {
  return <PlasmicButton {...props} />;
}

export default Button;
